version: "3.3"
services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: moretechdb
    restart: "always"
    ports:
      - 5432:5432
    volumes:
      #- ./postgres/data:/docker-entrypoint-initdb.d/
      - ./postgres/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nest:
    depends_on:
      - postgres
    image: node:20
    environment:
      DATABASE_HOST: postgres
    restart: "always"
    volumes:
      - ./nest-moretech/:/nest-moretech/
    ports:
      - 9000:8000
    working_dir: /nest-moretech/
    command: npm install 
    entrypoint: npm run start
    links:
      - "postgres:database"
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/../etc/letsencrypt/live/adera-team.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem        
      - ~/../etc/letsencrypt/live/adera-team.ru/privkey.pem:/etc/nginx/ssl/privkey.pem

    ports:
            - "8011:80"
            - "4431:443"

#  py:
#    image: python
#    volumes: 
#      - ./python:/app/
#    working_dir: /app
#    command:
#      bash -c "
#      pip install -r ./dependencies &&
#      cd app && 
#      gunicorn -k uvicorn.workers.UvicornWorker --log-level trace main:app -b :80
#      "
#    ports:
#      - 8003:80
